### ISSUE TITLE
[Server] JWT 토큰에 대한 Exception Handling 추가 및 보완 작업, API Security 적용 및 핸들링 추가 작업

### ISSUE THREAD

**Issue by shindonggeun** [SSoc-Student-SOCiety/SSoc#119]
## Description ✏
- Security와 JWT 토큰 설정이 완료됨에 따라 그에 따른 API를 권한에 따라 접근 가능하도록 수정할 예정입니다.
- 또한, RuntimeException으로 처리했던 예외를 핸들링할 예정입니다.
- jwt 토큰에 대한 자격증명 및 권한 없이 접근 할 경우 response 에러 응답을 간소화 할 예정입니다.

## Todo 📝
- [x] JWT 토큰 자격증명 및 권한 없이 접근 할 경우 Security config에서 filter내에서 처리 및 response 에러 응답 간소화하는 기능
- [x] 유저 및 그룹 가입 요청 관련들 api 권한에 따라 접근 가능하도록 수정
- [x] RuntimeException으로 처리했던 예외 핸들링하도록 수정
