### ISSUE TITLE
[Server] 그룹 관련 기초 엔티티 작성

### ISSUE THREAD

**Issue by Dokuny** [SSoc-Student-SOCiety/SSoc#14]
## Description ✏
- 그룹 및 그룹과 관련된 기초 엔티티를 작성할 예정입니다.

## Todo 📝
- [x] 그룹 엔티티 작성
- [x] 학교 엔티티 작성
- [x] 학교 이메일 작성

## ETC 📌
- CRUD 같은 부가적인 것은 후에 유저 개발이 마무리 되면 개발할 예정입니다.
- 수정날짜, 생성날짜 같은 컬럼은 추후에 JPA Audit을 통해 추가할 예정입니다.
