### ISSUE TITLE
[Server] 회원이 물품 예약 관련 기능 및 그룹 관리자가 회원들의 예약 물품 예약 승인 여부 처리 기능 구현, 유저 회원 탈퇴 기능 수정 및 보완

### ISSUE THREAD

**Issue by shindonggeun** [SSoc-Student-SOCiety/SSoc#140]
## Description ✏
- 회원이 그룹에서 제공하는 대여 물품을 예약할 수 있는 기능을 구현해야 합니다.
- 그룹 관리자가 해당 그룹의 대여 물품의 예약 내역을 조회하는 기능을 구현해야 합니다.
- 그룹 관리자가 회원들의 예약 물품 예약 승인 여부를 처리하는 기능을 구현해야 합니다.
- 유저가 회원 탈퇴를 할 경우 그룹에 가입되어 있는 경우 그룹에서 해당 멤버를 먼저 삭제 한 뒤 유저를 삭제해주도록 기능을 수정해야합니다.

## Todo 📝
- [x] 회원이 그룹에서 제공하는 대여 물품을 예약할 수 있는 기능 구현
- [x] 그룹 관리자가 해당 그룹의 예약 내역을 조회하는 기능 (전체 조회, 반납 여부에 따른 조회, 승인 여부에 따른 조회)
- [x] 그룹 관리자가 회원들의 예약 물품 예약 승인 여부를 처리하는 기능 구현
- [x] 유저가 회원 탈퇴를 할 경우 그룹에 가입되어 있는 경우 그룹에서 해당 멤버를 먼저 삭제 한 뒤 유저를 삭제해주도록 기능 수정 및 보완

## ETC 📌
- 남길 말을 적어주세요.
