### ISSUE TITLE
[Server] 유저 회원가입 기능 구현

### ISSUE THREAD

**Issue by shindonggeun** [SSoc-Student-SOCiety/SSoc#18]
## Description ✏
- 회원가입 시 필요한 정보들을 받아서 저장할 기능을 구현해야 합니다.

## Todo 📝
- [x] 회원가입 시 입력받은 정보들 DB에 저장하는 기능
- [x] db내에 데이터들 저장될 때 공통적으로 사용 될 creadedAt, updateAt 컬럼을 공통적으로 BaseEntity 추가 및 상속
- [x] 회원가입 시 이메일에 인증코드를 발송해 인증코드를 입력해야 회원가입이 완료되는 기능

## ETC 📌
-  회원가입시 입력받은 데이터들은 @RequestBody 어노테이션을 사용하여 JSON 형식을 자바 객체로 전달받을 예정입니다.
-  이메일 인증코드에 필요한 수신자 이메일은 @RequestParam 어노테이션을 사용하여 String으로 전달받을 예정입니다.
