### ISSUE TITLE
Issue: Client Setting 

### ISSUE THREAD

**Issue by dev1week** [SSoc-Student-SOCiety/SSoc#2]
## Description ✏
-Client 초기 세팅 

## Todo 📝
- [x] expo 설치 
- [x] 종속성 설치 
- [x] "react-native-safe-area-context": "^4.7.2",
- [x]  "react-native-screens": "^3.25.0"
- [x]     "@react-navigation/native": "^6.1.7",
- [x]    "@react-navigation/native-stack": "^6.9.13",
- [x]  eslint 설정 
- [x] prettier 설정 

## ETC 📌
- 기본적인 라이브러리 설치 후 이후 설치하는 라이브러리는 반드시 npm --save 옵션을 주어 설정합니다.

**Comment by dev1week** [comment]
confirm
