### ISSUE TITLE
[Server] Group CRUD 구현

### ISSUE THREAD

**Issue by Dokuny** [SSoc-Student-SOCiety/SSoc#28]
## Description ✏
- 기본적인 Group CRUD를 구현할 예정입니다.

## Todo 📝
- [x] 그룹 생성
- [x] 그룹 비활성화
- [x] 그룹 정보 변경
- [x] 전체 그룹 조회
- [x] 가입한 그룹 조회
- [x] 그룹 정보 조회

## ETC 📌
- 그룹 생성 및 비활성화는 Service Admin 권한
- 권한 체크는 Spring Security 구현된 이후에 적용할 예정

**Comment by Dokuny** [comment]
그룹 정보 변경에 썸네일 변경도 들어가야할 듯 합니다.
