### ISSUE TITLE
[Server] Spring Security 연동 및 JWT 토큰을 통한 로그인 / 로그아웃 기능 구현

### ISSUE THREAD

**Issue by shindonggeun** [SSoc-Student-SOCiety/SSoc#31]
## Description ✏
- Spring Security 연동과 더불어 JWT 토큰을 통한 로그인 기능을 구현해야 합니다.

## Todo 📝
- [x] Spring boot에 Spring security를 연동하여 JPA를 이용한 커스텀 로그인 처리 기능
- [x] 회원가입시 DB에 패스워드를 저장할 때 암호화해서 저장하게끔 하는 기능 (PasswordEncoder 이용)
- [x] Spring security를 연동한 로그아웃 처리 기능
- [x] 로그인 / 로그아웃 시 JWT 연동 기능

## ETC 📌
-  회원가입시 입력받은 데이터들은 @RequestBody 어노테이션을 사용하여 JSON 형식을 자바 객체로 전달받을 예정입니다.
-  이메일 인증코드에 필요한 수신자 이메일은 @RequestParam 어노테이션을 사용하여 String으로 전달받을 예정입니다.
