### ISSUE TITLE
[Client] Search Result Screen 개발

### ISSUE THREAD

**Issue by dev1week** [SSoc-Student-SOCiety/SSoc#40]
## Description ✏
- Issue에 대해 설명해주세요.
인터넷 이슈로 이따 적을게요...

## Todo 📝

- [x]  검색 옵션 카테고리 선택 구현
- [x]  검색 버튼 컴포넌트 분할
- [x]  검색 결과 및 검색 결과 아이템 컴포넌트 구현
- [x]  검색결과 스크린 적용
- [x]  main screen : mock 데이터 변수 분할 및 반복문으로 렌더링 처리
- [x]  main screen : 스타일 시트 이름 변경
- [x]  stackheader : 세팅 스크린으로 정상 이동
- [x]  profile image : 의미 없는 console.log 삭제
- [x]  main search bar : search button 컴포넌트 분할 적용

## ETC 📌
- 남길 말을 적어주세요.
