### ISSUE TITLE
[Client] Basic Components 

### ISSUE THREAD

**Issue by dev1week** [SSoc-Student-SOCiety/SSoc#5]
## Description ✏
- 디자인 시스템을 바탕으로 기본적인 컴포넌트들을 정의합니다. 
- 기본적인 atomic 컴포넌트들을 정의해 컴포넌트 재사용성을 높입니다. 

## Todo 📝
- [x] Button, Divider(구분자), Spacer(공백자),  Typography(텍스트) 컴포넌트 정의
- [x] Input 관련 컴포넌트 정의 
- [x] Header 관련 컴포넌트 정의 
- [x] Bottom Tab 관련 컴포넌트 정의 
- [x] Icon 관련 컴포넌트 정의
- [x] 이미지 관련 컴포넌트 정의 
- [x] 색상 상수 정의 
- [x] 관련 사용법 문서 정리  
## ETC 📌
-컴포넌트 정의 후 반드시 에뮬레이터/실제 기기에서 정상 렌더링이 되는지 확인 후 커밋 바랍니다.

**Comment by dev1week** [comment]
confirm
