### ISSUE TITLE
[Server] 신한은행 API 연동 컴포넌트 작성

### ISSUE THREAD

**Issue by Dokuny** [SSoc-Student-SOCiety/SSoc#6]
## Description ✏
- 신한은행 API와 연동하는 컴포넌트를 작성해야합니다.

## Todo 📝
- [x] 계좌 잔액 조회
- [x] 계좌 거래내역 조회
- [x] 예금주 실명 조회
- [x] 1원 이체
- [x] 이체

## ETC 📌
- OpenFeign을 이용하여 구현하되, 비동기 필요 시 교체할 수 있도록 Interface로 구현할 예정입니다.
- SOL 앱 푸시 기능은 회원 코드 등 제한 사항이 있어서 보류합니다.
