### ISSUE TITLE
[Server] 회원정보들을 저장하기 위한 User Entity 설정 및 셋업

### ISSUE THREAD

**Issue by shindonggeun** [SSoc-Student-SOCiety/SSoc#8]
## Description ✏
- 회원가입 시 유저 DB에 저장되는 User Entity를 작성해야 합니다.

## Todo 📝
- [x] User Entity 추가 
- [x] UserRoleSet Entity 추가
- [x] User Repository 추가
- [x] User Service 추가

## ETC 📌
- Repository에 JPA Repository 인터페이스를 상속받아서 사용할 예정입니다.
- 추가로 테스트 파일을 작성할 예정입니다.
